---
driver:
  name: vagrant
  gui: true
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  client_rb:
      add_formatter: doc

platforms:
  - name: debian8
    driver_config:
      box: debian/jessie64
    provisioner:
      require_chef_omnibus: 12.4.3

  - name: ubuntu1604
    driver_config:
      box: ubuntu/xenial64
    provisioner:
      require_chef_omnibus: 12.4.3

  - name: centos6
    driver_config:
      box: bento/centos-6.7
    provisioner:
      require_chef_omnibus: 12.4.3

# private boxes
  - name: osx109-desktop
    driver_config:
      box: osx109-desktop #private
    provisioner:
      require_chef_omnibus: 12.4.3

  - name: windows10
    driver_config:
      guest: windows
      communicator: 'winrm'
      box: win10x64-enterprise #private
    provisioner:
      require_chef_omnibus: 12.4.3

  - name: windows81
    driver_config:
      guest: windows
      communicator: 'winrm'
      box: win81x64-enterprise #private
    provisioner:
      require_chef_omnibus: 12.4.3


suites:
  - name: windows-basic
    run_list:
      - recipe[windows-basic::default]
    includes:
      - windows10
    attributes:
        vsts_agent_test:
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>
            
  - name: debian-basic
    run_list:
      - recipe[debian-basic::default]
    includes:
      - debian8
      - ubuntu1604
    attributes:
        vsts_agent_test:
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>

  - name: osx-basic
    run_list:
      - recipe[osx-basic::default]
    includes:
      - osx109-desktop

    attributes:
        vsts_agent_test:
            vsts_url: <%= ENV['VSTS_URL'] %>
            vsts_pool: <%= ENV['VSTS_POOL'] %>
            vsts_token: <%= ENV['VSTS_TOKEN'] %>
